---
title: "BGC_Climate_Summaries"
author: "William H MacKenzie"
date: "17/10/2019"
output: html_document
---
# R codes here are written to calculate climate summaries


# STEP 1: Prepare dataset for analysis----
# clear workspace
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list=ls())
require(tidyverse)
require(data.table)
require(sf)
library(dplyr)
library(rgdal)
library(sp)
library(raster)
library(rgeos)
library(maptools)
library(magrittr)
library(tibble)
library(tidyr)
library(sf)
library(tcltk)
library(foreach)
library(httr)
library(jsonlite)
library(randomForest)
library(data.table)
require(survey)
require(fasterize)
require(tibble)
require(maptools)
require(tictoc)
```

#Choose file = Normal Period ClimateWNA output with BGC
-- all variables time series 1901-latest

```{r input data, echo=FALSE}
CRS.albers <- CRS ("+proj=aea +lat_1=50 +lat_2=58.5 +lat_0=45 +lon_0=-126 +x_0=1000000 +y_0=0 +datum=NAD83 +units=m +no_defs")
CRS.NAD83 <- CRS("+init=epsg:4269")

a <-file.choose() #points file with climate data
BGC <-file.choose()#spatial file of BGC
fname <-basename(a)
mydata <- fread(a) #(read in CSV)
mydata$lat <- mydata$Latitude
mydata$long <- mydata$Longitude
#mydata2 <- mydata[mydata$State == "BC",] #limit locations to BC
mydata_spatial <-  st_as_sf (mydata, coords = c("Longitude", "Latitude"), crs = CRS.NAD83) %>% st_transform(CRS.albers)

BGC_spatial <-  read_sf (BGC) %>% st_set_crs (CRS.albers)

mydata3 <- st_join(mydata_spatial, BGC_spatial) %>% st_transform(CRS.NAD83)### add BGC variables to climate data
mydata4 <- as.data.frame(mydata3) %>% drop_na("State")
mydata4 <- mydata4 %>% dplyr::select("ID1", "State", "BGC", "lat", "long", "Elevation", everything())
mydata4 <- mydata4[!(mydata4$MAT == -9999.0),] # removes [points that are outside of climateBC model]
write.csv(mydata4, a) ##replaces the orginal file
save(mydata4,file=paste0("./outputs/",fname,".Rdata",sep="")) # save as an RDA for future applications


```

 ## Summarize normal period climate variables by BGC for a number of points

```{r summarize by BGC, echo=FALSE}
#read in an existing dataset

var.remove <- c("ID1","lat", "long", "Elevation", "geometry" )
mydata5 <- dplyr::select (mydata4,-var.remove) # Drop Lat, Long, Elevation
#mydata2[-1] <- lapply(mydata2[-1], as.numeric)

#var.list <- c("BGC","MAT", "Tave_sm", "MAP", "MSP", "PAS", "CMD", "TD" ) # for BGC subzone designation
var.list <- c("CMD", "DD5") # for SI50 calculations
#mydata3 <- select (mydata2, var.list) 

mydata6 <- mydata5 %>% dplyr:: select("BGC",var.list, starts_with("DD5"), starts_with("DD18"), starts_with("Tmax")) %>% drop_na()
pts_BGC <- mydata4 %>% 
  group_by(BGC) %>% summarize (n = n() , na.rm = TRUE)
pts_BGC

### summarize by select list of variables
BGC_climate <- mydata4 %>% 
  group_by(BGC) %>% summarize_at(vars(var.list) , funs(mean, sd),na.rm = TRUE)

###summarize by all variables in a reduced variable data set
 BGC_climate <- mydata6 %>% 
   group_by(BGC) %>%
   #summarize_all(list (~mean(.), ~min(.), ~max(.)), na.rm = TRUE)
summarize_all(list (~mean(.), na.rm = TRUE))
BGC.list <- as.list(mydata6$BGC)
BGC.count <- mydata6 [,lapply(length), by = BGC]
write.csv (by_BGC, "./outputs/WNA_Climate_Means_by_BGC_from_4Km.csv")
```


##Plot variables by BGC

```{r plots of variables}

```
